### ISSUE TITLE
Question regarding some-math-notes/exercises/zachmonoglou-thoe/

### ISSUE THREAD

**Issue by NoahPinel** [Aidenwjt/some-math-notes#1]
Bonsoir Aiden, 
Nice proof for question 1.1 but your result is limited to that of metric spaces, which is understandable because you are mainly working in $R^n$. I challenge you to produce a proof for generality, that is: "prove that a closed set X contains all its limit points, but instead of a metric space, consider the more general topological space $\tau$".

Cheers,
Noah

**Comment by Aidenwjt** [comment]
💀

**Comment by NoahPinel** [comment]
:chills:
